# docker-compose up -d --scale worker=1 --build
# stripe listen --forward-to localhost:8000/payment/webhook/
#
# Resullt                           | Test credit card    | CVC          | Expiracy date
# -----------------------------------------------------------------------------------------
# Successful payment                | 4242 4242 4242 4242 | Any 3 digits | Any future date
# Failed payment                    | 4000 0000 0000 0002 | Any 3 digits | Any future date
# Requires 3D secure authentication | 4000 0025 0000 3155 | Any 3 digits | Any future date
version: '3.9'

services:

  db:
    image: postgres:latest
    container_name: vr_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=vr_shop"

  broker:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - db
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  flower:
    image: zoomeranalytics/flower:0.9.1-4.0.2
    restart: "no"
    command: bash -c "celery flower --port=5555 --broker=amqp://admin:admin@broker:5672/"
    ports:
      - "5555:5555"
    depends_on:
      - broker
      - web

  web: &web
    build: .
    image: backend-image
    container_name: vr_web
    ports:
      - "8000:8000"
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./media:/code/media
    depends_on:
      - db
      - broker
      - redis
    environment:
    - "DJANGO_KEY_FILE: '/run/secrets/django-secrets'"
    secrets:
      - django-secrets
  
  worker:
    <<: *web
    restart: on-failure
    container_name: worker
    environment:
      - CELERY_BROKER=amqp://admin:admin@broker:5672//
    command: celery -A config worker -l info
    ports: []
    depends_on:
      - broker
      - db

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

secrets:
  django-secrets:
    file: ./config/.env
