# Generated by Django 4.1.7 on 2023-03-18 08:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
